title: Raising Voices in Closing Spaces
title_full: Raising Voices in Closing Spaces
title_full_br: Raising Voices in <br />Closing Spaces
subtitle: Strategic Communications Planning for Nonpartisan Citizen Election Observer Groups
description: >- # this means to ignore newlines until "baseurl:"
  This guide offers a step-by-step approach to strategic communications planning and programming in closing political spaces. It offers strategies, tactics and case studies for civil society groups operating in repressive environments.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://raiseavoice.net/" # the base hostname & protocol for your site, e.g. http://example.com

# Social
email: openelectiondata@ndi.org
facebook: "National.Democratic.Institute"
twitter: ndi
instagram: ndidemocracy

# Theme Settings
search_enabled: true
permalink: pretty

# Collections
collections:
  posts:
    output: false
  guide:
    title: Guide
    output: true

defaults:
  - scope:
      path: ""
      type: "guide"
    values:
      layout: page
      permalink: "/:slug/"

# Translation Settings
languages: ["en", "es"]
default_lang: "en"
exclude_from_localization: ["assets"]
parallel_localization: true

jekyll-figure:
  paragraphs: false

# Build settings
markdown: kramdown
kramdown:
  auto_ids: true
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-polyglot
  - jekyll-figure
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
