---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: _guide
  label: 'Guide: English'
  create: documents
  match: "*.en.md"
  new_doc_ext: ".en.md"
- type: directory
  path: _guide
  label: 'Guide: Spanish'
  create: documents
  match: "**/*.es.md"
  new_doc_ext: es.md
- type: document
  path: _data/menus.yml
  label: Menus
- type: jekyll-pages
  label: Pages
  create: all
upload_dir: assets/images
public_path: "/assets/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
instant_preview: 
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d _site
  publish_command: bundle exec jekyll build -d _site
  publish_env:
  - JEKYLL_ENV=production
  output_directory: _site
  preview_command: bundle exec jekyll build --drafts --unpublished --future -d _site
