---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: document
  path: config.json
  label: Settings
- type: directory
  path: ''
  label: All Pages
  create: all
  match: "**/*.md"
  new_doc_ext: md
- type: directory
  path: ''
  label: English
  create: documents
  match: "*.md"
  new_doc_ext: ".md"
- type: directory
  path: es
  label: Spanish
  create: documents
  match: "**/*.md"
  new_doc_ext: md
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
instant_preview: true
build:
  preview_command: vuepress build -d .vuepress/dist
  publish_command: vuepress build -d .vuepress/dist
  preview_output_directory: ".vuepress/dist"
  output_directory: ".vuepress/dist"
  instant_preview_command: vuepress dev -p 8080 -h 0.0.0.0
  install_dependencies_command: yarn install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
