---
new_page_extension: md
auto_deploy: false
admin_path: "/admin"
webhook_url:
sections:
  - type: directory
    path: _guide
    label: "Guide: English"
    create: documents
    match: "*.en.md"
    new_doc_ext: en.md
    templates:
      - guide-pages
  - type: directory
    path: _guide
    label: "Guide: Spanish"
    create: documents
    match: "**/*.es.md"
    new_doc_ext: es.md
    templates:
      - guide-pages
  - type: directory
    path: _guide
    label: "Guide: Russian"
    create: documents
    match: "**/*.ru.md"
    new_doc_ext: ru.md
    templates:
      - guide-pages
  - type: directory
    path: _guide
    label: "Guide: Arabic"
    create: documents
    match: "**/*.ar.md"
    new_doc_ext: ar.md
    templates:
      - guide-pages
  - type: document
    path: _data/menus.yml
    label: Menus
  - type: jekyll-pages
    label: Other Pages
    create: documents
  - type: heading
    label: Translations
  - type: document
    path: _data/en/strings.yml
    label: English
  - type: document
    path: _data/es/strings.yml
    label: Spanish
  - type: document
    path: _data/ru/strings.yml
    label: Russian
  - type: document
    path: _data/ar/strings.yml
    label: Arabic
upload_dir: assets/images
public_path: "/assets/images"
front_matter_path: ""
use_front_matter_path: false
file_template: ":filename:"
instant_preview: true
build:
  preview_env:
    - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command:
    bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d _site
  preview_command: bundle exec jekyll build --drafts --unpublished --future -d _site
