---
label: Settings
hide_body: true
fields:
- type: text
  name: title
  label: title
- type: list
  name: sidebar
  label: sidebar
  config:
    use_select: true
    source:
      type: pages
      section: pages
